version: "3.9"
services:
  cuillere-api-postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: cuillere-api
      POSTGRES_USER: cuillere-api
      POSTGRES_PASSWORD: mysecretpassword


  # Zookeeper, nécessaire pour le kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost


  # Akhq, interface admin pour kafka (url : http://localhost:19000/ui/docker-kafka-server)
  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: "connect"
                  url: "http://connect:8083"

networks:
  broker-kafka:
    driver: bridge